---
repo:
  scanPath: /Users/prologic/Projects
  readme:
    - readme
    - README
    - readme.md
    - README.md
  license:
    - license
    - LICENSE
    - license.txt
    - LICENSE.txt
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: git good
  description: i think it's a skill issue
server:
  name: localhost
  host: 127.0.0.1
  httpPort: 5555
  sshPort: 2222
